version: 0.0
os: linux 
files:
  - source: /
    destination: /home/ec2-user/TradeTrackerIM
permissions:
  - object: /home/ec2-user/TradeTrackerIM
    owner: ec2-user
    group: nginx
    mode: 664
    type:
      - file
hooks:
  #ApplicationStop: 
    - location: scripts/ApplicationStop.sh
      timeout: 180
      runas: root
# During the BeforeInstall deployment lifecycle event, run the commands 
#   in the script specified in "location".
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 180
      runas: root
# During the AfterInstall deployment lifecycle event, run the commands 
#   in the script specified in "location".
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 180
      runas: ec2-user
# During the ApplicationInstall deployment lifecycle event, run the commands 
#   in the script specified in "location".
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout: 180
      runas: root
# During the ValidateService deployment lifecycle event, run the commands 
#   in the script specified in "location".
  ValidateService:
    - location: scripts/ValidateService.sh
      timeout: 180
      runas: root
